### PR TITLE
Improve Erlang.xml

### PR DESCRIPTION
**Pull request by davisp**
This uses the Erlang.plist definitions from the Erlang TextMate bundle
to redefine the entire Erlang syntax definition. The included tm2nova.py
script does a first pass at the translation however a decent amount of
manual tweaking is required to provide a functioning Erlang syntax for
Nova.app

### CODE REVIEW

**Comment by davisp** [comment]
This covers quite a bit of Erlang syntax. Things that are noticeably missing are map and type support which didn't exist in the TextMate bundle and will need to be added.

**Comment by janl** [comment]
@davisp this is phenomenal. I tried it and it looks fine overall, but the function arity highlighting is a bit jarring. I tried fiddling with things a bit, but didn’t get anywhere in particular. Any ideas?

Screenshot 2020-10-06 at 16 23 09
Screenshot 2020-10-06 at 16 23 28

**Comment by janl** [comment]
of course I find the culprit right after posting this:

```diff
diff --git a/Syntaxes/Erlang.xml b/Syntaxes/Erlang.xml
index efcad86..8c9cf9d 100644
--- a/Syntaxes/Erlang.xml
+++ b/Syntaxes/Erlang.xml
@@ -853,9 +853,9 @@
             <expression>36(\#)[\da-zA-Z]++</expression>
             <capture number="1" name="erlang.operator.numeric-base" />
           </scope>
-          <scope name="erlang.invalid">
+          <!-- <scope name="erlang.invalid">
             <expression>\d++#[\da-zA-Z]++</expression>
-          </scope>
+          </scope> -->
           <scope name="erlang.value.number.integer">
             <expression>\d++</expression>
           </scope>

```

**Comment by davisp** [comment]
Good catch! That # needs to be escaped. Something about the different regexp engines requires that in a lot of places compared to the original TM bundle. Will update with the fix.

**Comment by davisp** [comment]
Fixed the number issue and added support for parsing maps.

**Pull request merged**
